[general]
background = "#020F01"
border = "#020E01"
horizontal_rule = "#1C451A"
unread_indicator = "#FB4502"

[text]
primary = "#EAED86"
secondary = "#02AE16"
tertiary = "#02AE16"
success = "#02AE16"
error = "#E90303"

[buffer]
action = "#36C7C5"
background = "#051203"
background_text_input = "#020E01"
background_title_bar = "#020E01"
border = "#0A1A0A"
border_selected = "#1C451A"
code = "#02AE16"
highlight = "#29362A"
nickname = "#02AE16"
selection = "#353836"
timestamp = "#02AE16"
topic = "#02AE16"
url = "#02AE16"

  [buffer.server_messages]
  join = "#00000000"
  default = "#02AE16"

[buttons.primary]
background = "#00000000"
background_hover = "#1D1D1D"
background_selected = "#272727"
background_selected_hover = "#363636"

[buttons.secondary]
background = "#242424"
background_hover = "#282828"
background_selected = "#1C451A"
background_selected_hover = "#1C451A"

