[general]
background = "#2C2E34"
border = "#414550"
horizontal_rule = "#3B3E48"
unread_indicator = "#E7C664"

[text]
primary = "#E2E2E3"
secondary = "#7F8490"
tertiary = "#F39660"
success = "#9ED072"
error = "#FC5D7C"

[buffer]
action = "#B39DF3"
background = "#33353F"
background_text_input = "#2C2E34"
background_title_bar = "#222327"
border = "#3B3E48"
border_selected = "#76CCE0"
code = "#F39660"
highlight = "#363944"
nickname = "#76CCE0"
selection = "#363944"
timestamp = "#595F6F"
topic = "#7F8490"
url = "#76CCE0"

  [buffer.server_messages]
  default = "#7F8490"

[buttons.primary]
background = "#33353F"
background_hover = "#2C2E34"
background_selected = "#222327"
background_selected_hover = "#181819"

[buttons.secondary]
background = "#414550"
background_hover = "#3B3E48"
background_selected = "#76CCE0"
background_selected_hover = "#85D3F2"

